import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Pugmark Footprints Training Notebook\n",
                "\n",
                "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/nicholasmartino/pugmark/blob/master/notebooks/train_footprints.ipynb)\n",
                "\n",
                "This notebook implements the training pipeline for the footprints model.\n",
                "It can be run manually in Google Colab or programmatically via GitHub Actions.",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Parameters\n",
                "\n",
                "The cell below defines parameters that can be injected by Papermill when running this notebook programmatically.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"tags": ["parameters"]},
            "outputs": [],
            "source": [
                "# These parameters can be overridden by Papermill\n",
                "# Default values are used when running in Colab\n",
                "EPOCHS = 50  # Number of training epochs",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Setup and Dependencies\n",
                "\n",
                "First, let's install required packages and set up authentication for Google Cloud Storage.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Check if running in Colab\n",
                "import sys\n",
                "IN_COLAB = 'google.colab' in sys.modules\n",
                "\n",
                "if IN_COLAB:\n",
                "    !pip install gcsfs tensorflow\n",
                "    # Clone the repository if in Colab\n",
                "    !git clone https://github.com/nicholasmartino/pugmark.git\n",
                "    %cd pugmark\n",
                "    \n",
                "    # Authenticate to GCP\n",
                "    from google.colab import auth\n",
                "    auth.authenticate_user()\n",
                "else:\n",
                "    # When running through GitHub actions, auth will be handled differently\n",
                '    print("Running outside of Colab - assuming authentication is already set up")',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import necessary libraries\n",
                "import datetime\n",
                "import os\n",
                "import time\n",
                "import sys\n",
                "\n",
                "import gcsfs\n",
                "import tensorflow as tf\n",
                "from IPython import display\n",
                "\n",
                "# Ensure the src directory is in the Python path\n",
                "if not IN_COLAB:\n",
                "    module_path = os.path.abspath(os.path.join('..'))\n",
                "    if module_path not in sys.path:\n",
                "        sys.path.append(module_path)\n",
                "else:\n",
                "    # In Colab, we're already in the pugmark directory\n",
                "    if '.' not in sys.path:\n",
                "        sys.path.append('.')",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import project modules\n",
                "from src.training.Discriminator import Discriminator, calculate_discriminator_loss\n",
                "from src.training.Generator import Generator, calculate_generator_loss, generate_images\n",
                "from src.training.Globals import *  # This will import PATH and BATCH_SIZE, but we'll override EPOCHS with our parameter\n",
                "from src.training.Loader import load, load_image_test, load_image_train\n",
                "from src.training.Sampler import downsample, upsample\n",
                "\n",
                "# Setup authentication\n",
                "if IN_COLAB:\n",
                "    # Use Google Cloud authenticated client\n",
                "    from google.cloud import storage\n",
                "    client = storage.Client()\n",
                "else:\n",
                "    # Import the auth utilities when running outside Colab\n",
                "    from src.training.AuthUtils import auth_client_locally, auth_client_from_cloud\n",
                '    if os.getenv("CLOUD_RUN_JOB"):  # This environment variable is present in Cloud Run\n',
                '        print("Running in Google Cloud environment")\n',
                "        client = auth_client_from_cloud()\n",
                "    else:\n",
                '        print("Running locally")\n',
                "        client = auth_client_locally()",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Print configuration\n",
                'print(f"Training configuration:")\n',
                'print(f"- Epochs: {EPOCHS}")\n',
                'print(f"- Batch size: {BATCH_SIZE}")\n',
                'print(f"- Data path: {PATH}")\n',
                "\n",
                "# Verify bucket access\n",
                'bucket = client.get_bucket("metro-vancouver-regional-district")\n',
                'print(f"Bucket exists: {bucket.exists()}")\n',
                "\n",
                "# Update paths to use GCS\n",
                'log_dir = tf.io.gfile.join(PATH, "footprints/logs")\n',
                'checkpoint_dir = tf.io.gfile.join(PATH, "footprints/checkpoint")\n',
                "\n",
                "# Ensure log directory exists\n",
                "tf.io.gfile.makedirs(log_dir)\n",
                "\n",
                "# Initialize summary writer with GCS-compatible path\n",
                "summary_writer = tf.summary.create_file_writer(\n",
                '    tf.io.gfile.join(log_dir, "fit", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))\n',
                ")",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Data Loading and Preprocessing"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Setup GCS filesystem and load paths\n",
                "fs = gcsfs.GCSFileSystem()\n",
                'train_files = fs.ls(os.path.join(PATH, "footprints/train"))\n',
                'test_files = fs.ls(os.path.join(PATH, "footprints/test"))\n',
                "\n",
                "# Update file listing to use full paths\n",
                'test_files = tf.io.gfile.glob(f"{PATH}/footprints/test/*.png")\n',
                'input_image, real_image = load(f"{test_files[0]}")\n',
                "print(input_image.shape)\n",
                "\n",
                "# Setup datasets\n",
                'train_dataset = tf.data.Dataset.list_files(f"{PATH}/footprints/train/*.png")\n',
                "train_dataset = train_dataset.shuffle(buffer_size=1000)\n",
                "train_dataset = train_dataset.map(load_image_train, num_parallel_calls=tf.data.AUTOTUNE)\n",
                "train_dataset = train_dataset.batch(BATCH_SIZE)\n",
                "train_dataset = train_dataset.repeat()\n",
                "print(train_dataset.element_spec[0])\n",
                "\n",
                'test_dataset = tf.data.Dataset.list_files(f"{PATH}/footprints/test/*.png")\n',
                "test_dataset = test_dataset.map(load_image_test)\n",
                "test_dataset = test_dataset.batch(BATCH_SIZE)",
            ],
        },
        {"cell_type": "markdown", "metadata": {}, "source": ["## Model Architecture"]},
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Test the downsampling and upsampling functions\n",
                "down_model = downsample(3, 4)\n",
                "down_result = down_model(tf.expand_dims(input_image, 0))\n",
                "print(down_result.shape)\n",
                "\n",
                "up_model = upsample(3, 4)\n",
                "up_result = up_model(down_result)\n",
                "print(up_result.shape)\n",
                "\n",
                "# Initialize the generator\n",
                "generator = Generator()\n",
                "generated = generator(input_image[tf.newaxis, ...], training=False)\n",
                "\n",
                "# Initialize the discriminator\n",
                "discriminator = Discriminator()\n",
                "discriminated = discriminator([input_image[tf.newaxis, ...], generated], training=False)\n",
                "\n",
                "# Test the model by generating an image\n",
                "for example_input, example_target in test_dataset.take(1):\n",
                "    generate_images(generator, example_input, example_target)",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Training Configuration"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Setup the loss function and optimizers\n",
                "loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=True)\n",
                "generator_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)\n",
                "discriminator_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)\n",
                "\n",
                "# Checkpoint setup\n",
                "checkpoint = tf.train.Checkpoint(\n",
                "    generator_optimizer=generator_optimizer,\n",
                "    discriminator_optimizer=discriminator_optimizer,\n",
                "    generator=generator,\n",
                "    discriminator=discriminator,\n",
                ")",
            ],
        },
        {"cell_type": "markdown", "metadata": {}, "source": ["## Training Functions"]},
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "@tf.function\n",
                "def train_step(input_image, target, epoch):\n",
                "    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:\n",
                "        generated = generator(input_image, training=True)\n",
                "\n",
                "        target_score = discriminator([input_image, target], training=True)\n",
                "        generated_score = discriminator([input_image, generated], training=True)\n",
                "\n",
                "        generator_total_loss, generator_gan_loss, generator_l1_loss = (\n",
                "            calculate_generator_loss(generated_score, generated, target, loss_object)\n",
                "        )\n",
                "        discriminator_loss = calculate_discriminator_loss(\n",
                "            target_score, generated_score, loss_object\n",
                "        )\n",
                "\n",
                "    generator_gradients = gen_tape.gradient(\n",
                "        generator_total_loss, generator.trainable_variables\n",
                "    )\n",
                "    discriminator_gradients = disc_tape.gradient(\n",
                "        discriminator_loss, discriminator.trainable_variables\n",
                "    )\n",
                "\n",
                "    generator_optimizer.apply_gradients(\n",
                "        zip(generator_gradients, generator.trainable_variables)\n",
                "    )\n",
                "    discriminator_optimizer.apply_gradients(\n",
                "        zip(discriminator_gradients, discriminator.trainable_variables)\n",
                "    )\n",
                "\n",
                "    with summary_writer.as_default():\n",
                '        tf.summary.scalar("gen_total_loss", generator_total_loss, step=epoch)\n',
                '        tf.summary.scalar("gen_gan_loss", generator_gan_loss, step=epoch)\n',
                '        tf.summary.scalar("gen_l1_loss", generator_l1_loss, step=epoch)\n',
                '        tf.summary.scalar("disc_loss", discriminator_loss, step=epoch)',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def fit(train_dataset, test_dataset, generator, checkpoint, checkpoint_directory, epochs):\n",
                '    checkpoint_prefix = os.path.join(checkpoint_directory, "ckpt")\n',
                "    start_time = time.time()\n",
                "    \n",
                "    for epoch in range(epochs):\n",
                "        epoch_start = time.time()\n",
                "\n",
                "        display.clear_output(wait=True)\n",
                "\n",
                "        for ex_input, ex_target in test_dataset.take(1):\n",
                "            generate_images(generator, ex_input, ex_target)\n",
                '        print(f"Epoch: {epoch}")\n',
                "\n",
                "        # Train\n",
                '        print("Training...")\n',
                "        for n, (input_image, target) in train_dataset.enumerate():\n",
                '            print(".", end="")\n',
                "            if (n + 1) % 100 == 0:\n",
                "                print()\n",
                "            train_step(input_image, target, epoch)\n",
                "            # Limit number of batches per epoch for faster iterations when debugging\n",
                "            if (n + 1) % 500 == 0:  # Adjust this number based on dataset size\n",
                "                break\n",
                "\n",
                "        # saving (checkpoint) the model every 20 epochs\n",
                "        if (epoch + 1) % 20 == 0:\n",
                "            checkpoint.save(file_prefix=checkpoint_prefix)\n",
                "\n",
                "        print(\n",
                '            f"Time taken for epoch {epoch + 1} is {time.time() - epoch_start:.2f} sec\\n"\n',
                "        )\n",
                "        \n",
                "    # Save final checkpoint\n",
                "    checkpoint.save(file_prefix=checkpoint_prefix)\n",
                '    print(f"Total training time: {(time.time() - start_time)/60:.2f} minutes")',
            ],
        },
        {"cell_type": "markdown", "metadata": {}, "source": ["## Start Training"]},
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def train():\n",
                "    # Add verification checks\n",
                '    print("TensorFlow version:", tf.__version__)\n',
                '    print("GPU devices:", tf.config.list_physical_devices("GPU"))\n',
                "\n",
                "    # Force GPU placement test\n",
                '    with tf.device("/GPU:0"):\n',
                "        test_tensor = tf.random.normal([2, 2])\n",
                '        print("\\nTensor device test:", test_tensor.device)\n',
                "\n",
                "    # Training code\n",
                "    fit(train_dataset, test_dataset, generator, checkpoint, checkpoint_dir, EPOCHS)\n",
                "\n",
                "    # Restore the latest checkpoint\n",
                "    checkpoint.restore(tf.train.latest_checkpoint(checkpoint_dir))\n",
                "    \n",
                '    print("Training completed successfully!")\n',
                "    return generator  # Return the trained generator model",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Execute training\n",
                'if __name__ == "__main__" or IN_COLAB:\n',
                "    try:\n",
                "        trained_model = train()\n",
                '        print("Training completed successfully!")\n',
                "    except Exception as e:\n",
                '        print(f"An error occurred during training: {e}")',
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.10",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

# Write the notebook to file
os.makedirs("notebooks", exist_ok=True)
with open("notebooks/train_footprints.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)

print("Notebook created successfully!")
