name: Trigger Training
on: [push]

jobs:
  submit-training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Submit Job
        run: |
          gcloud ai-platform jobs submit training ${JOB_NAME}_$(date +%s) \
            --region=$REGION \
            --package-path=./trainer \
            --module-name=trainer.task \
            --staging-bucket=gs://$BUCKET_NAME
        env:
          JOB_NAME: building-footprint-pix2pix
          REGION: us-central1
          BUCKET_NAME: metro-vancouver-regional-district
